// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"
import "github.com/IKarasev/bcatt/internal/globals"

func TabVisualBody(graphAttr templ.Attributes, forkAttr templ.Attributes) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col w-full h-full bg-gray-100 overflow-y-scroll\"><div class=\"flex flex-row ps-8 pt-2\"><span class=\"font-sans font-medium text-lg text-black\">Карта сети</span></div><div class=\"flex flex-row w-full\"><div id=\"graph\" class=\"flex flex-row w-full h-[600px] py-2\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, graphAttr)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("></div><div id=\"latency-legend\"><h4>Connection Latency (ms)</h4><svg width=\"200\" height=\"20\"><linearGradient id=\"gradient\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"0%\"><stop offset=\"0%\" stop-color=\"#2ca02c\"></stop> <stop offset=\"50%\" stop-color=\"#ffd700\"></stop> <stop offset=\"100%\" stop-color=\"#d62728\"></stop></linearGradient> <rect width=\"200\" height=\"20\" fill=\"url(#gradient)\"></rect> <text x=\"0\" y=\"35\">0</text> <text x=\"90\" y=\"35\">100</text> <text x=\"180\" y=\"35\">200+</text></svg></div></div><hr class=\"border-slate-300\"><div class=\"flex flex-row ps-8 pt-2\"><span class=\"font-sans font-medium text-lg text-black\">Цепочка и ответвления блоков</span></div><div class=\"flex flex-row w-full py-2\"><div id=\"chainfork\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, forkAttr)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("></div></div></div><script src=\"/static/visual.js\"></script><!--<script src=\"/static/fork.js\"></script>-->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func TabVisual() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = TabVisualBody(
			templ.Attributes{
				"hx-trigger": fmt.Sprintf("sse:%s", globals.RSS_NET_UPDATE),
				fmt.Sprintf("hx-on:sse:%s", globals.RSS_NET_UPDATE): "updateGraph(event.detail)",
			},
			templ.Attributes{
				"hx-trigger": fmt.Sprintf("sse:%s", globals.RSS_FORK_UPDATE),
				fmt.Sprintf("hx-on:sse:%s", globals.RSS_FORK_UPDATE): "forkUpdate(event.detail)",
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
